'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.WebService2Soap")>  _
    Public Interface WebService2Soap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/obtenerCotizacion", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function obtenerCotizacion(ByVal fecha As Date) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/obtenerCotizacion", ReplyAction:="*")>  _
        Function obtenerCotizacionAsync(ByVal fecha As Date) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/registrarCotizacion", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function registrarCotizacion(ByVal fecha As Date, ByVal monto As Decimal) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/registrarCotizacion", ReplyAction:="*")>  _
        Function registrarCotizacionAsync(ByVal fecha As Date, ByVal monto As Decimal) As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebService2SoapChannel
        Inherits ServiceReference1.WebService2Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebService2SoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.WebService2Soap)
        Implements ServiceReference1.WebService2Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function obtenerCotizacion(ByVal fecha As Date) As System.Data.DataSet Implements ServiceReference1.WebService2Soap.obtenerCotizacion
            Return MyBase.Channel.obtenerCotizacion(fecha)
        End Function
        
        Public Function obtenerCotizacionAsync(ByVal fecha As Date) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements ServiceReference1.WebService2Soap.obtenerCotizacionAsync
            Return MyBase.Channel.obtenerCotizacionAsync(fecha)
        End Function
        
        Public Function registrarCotizacion(ByVal fecha As Date, ByVal monto As Decimal) As String Implements ServiceReference1.WebService2Soap.registrarCotizacion
            Return MyBase.Channel.registrarCotizacion(fecha, monto)
        End Function
        
        Public Function registrarCotizacionAsync(ByVal fecha As Date, ByVal monto As Decimal) As System.Threading.Tasks.Task(Of String) Implements ServiceReference1.WebService2Soap.registrarCotizacionAsync
            Return MyBase.Channel.registrarCotizacionAsync(fecha, monto)
        End Function
    End Class
End Namespace
