//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioSegip.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoApellidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ci {
            get {
                return this.CiField;
            }
            set {
                if ((object.ReferenceEquals(this.CiField, value) != true)) {
                    this.CiField = value;
                    this.RaisePropertyChanged("Ci");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PrimerApellido {
            get {
                return this.PrimerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerApellidoField, value) != true)) {
                    this.PrimerApellidoField = value;
                    this.RaisePropertyChanged("PrimerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SegundoApellido {
            get {
                return this.SegundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoApellidoField, value) != true)) {
                    this.SegundoApellidoField = value;
                    this.RaisePropertyChanged("SegundoApellido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NumeroDocumento del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarPersonaCI", ReplyAction="*")]
        ServicioSegip.ServiceReference1.BuscarPersonaCIResponse BuscarPersonaCI(ServicioSegip.ServiceReference1.BuscarPersonaCIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarPersonaCI", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioSegip.ServiceReference1.BuscarPersonaCIResponse> BuscarPersonaCIAsync(ServicioSegip.ServiceReference1.BuscarPersonaCIRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento PrimerApellido del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarPersonas", ReplyAction="*")]
        ServicioSegip.ServiceReference1.BuscarPersonasResponse BuscarPersonas(ServicioSegip.ServiceReference1.BuscarPersonasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarPersonas", ReplyAction="*")]
        System.Threading.Tasks.Task<ServicioSegip.ServiceReference1.BuscarPersonasResponse> BuscarPersonasAsync(ServicioSegip.ServiceReference1.BuscarPersonasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarPersonaCIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarPersonaCI", Namespace="http://tempuri.org/", Order=0)]
        public ServicioSegip.ServiceReference1.BuscarPersonaCIRequestBody Body;
        
        public BuscarPersonaCIRequest() {
        }
        
        public BuscarPersonaCIRequest(ServicioSegip.ServiceReference1.BuscarPersonaCIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarPersonaCIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NumeroDocumento;
        
        public BuscarPersonaCIRequestBody() {
        }
        
        public BuscarPersonaCIRequestBody(string NumeroDocumento) {
            this.NumeroDocumento = NumeroDocumento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarPersonaCIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarPersonaCIResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServicioSegip.ServiceReference1.BuscarPersonaCIResponseBody Body;
        
        public BuscarPersonaCIResponse() {
        }
        
        public BuscarPersonaCIResponse(ServicioSegip.ServiceReference1.BuscarPersonaCIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarPersonaCIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServicioSegip.ServiceReference1.Persona BuscarPersonaCIResult;
        
        public BuscarPersonaCIResponseBody() {
        }
        
        public BuscarPersonaCIResponseBody(ServicioSegip.ServiceReference1.Persona BuscarPersonaCIResult) {
            this.BuscarPersonaCIResult = BuscarPersonaCIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarPersonasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarPersonas", Namespace="http://tempuri.org/", Order=0)]
        public ServicioSegip.ServiceReference1.BuscarPersonasRequestBody Body;
        
        public BuscarPersonasRequest() {
        }
        
        public BuscarPersonasRequest(ServicioSegip.ServiceReference1.BuscarPersonasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarPersonasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PrimerApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SegundoApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombres;
        
        public BuscarPersonasRequestBody() {
        }
        
        public BuscarPersonasRequestBody(string PrimerApellido, string SegundoApellido, string Nombres) {
            this.PrimerApellido = PrimerApellido;
            this.SegundoApellido = SegundoApellido;
            this.Nombres = Nombres;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarPersonasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarPersonasResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServicioSegip.ServiceReference1.BuscarPersonasResponseBody Body;
        
        public BuscarPersonasResponse() {
        }
        
        public BuscarPersonasResponse(ServicioSegip.ServiceReference1.BuscarPersonasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarPersonasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServicioSegip.ServiceReference1.Persona[] BuscarPersonasResult;
        
        public BuscarPersonasResponseBody() {
        }
        
        public BuscarPersonasResponseBody(ServicioSegip.ServiceReference1.Persona[] BuscarPersonasResult) {
            this.BuscarPersonasResult = BuscarPersonasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ServicioSegip.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ServicioSegip.ServiceReference1.WebService1Soap>, ServicioSegip.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioSegip.ServiceReference1.BuscarPersonaCIResponse ServicioSegip.ServiceReference1.WebService1Soap.BuscarPersonaCI(ServicioSegip.ServiceReference1.BuscarPersonaCIRequest request) {
            return base.Channel.BuscarPersonaCI(request);
        }
        
        public ServicioSegip.ServiceReference1.Persona BuscarPersonaCI(string NumeroDocumento) {
            ServicioSegip.ServiceReference1.BuscarPersonaCIRequest inValue = new ServicioSegip.ServiceReference1.BuscarPersonaCIRequest();
            inValue.Body = new ServicioSegip.ServiceReference1.BuscarPersonaCIRequestBody();
            inValue.Body.NumeroDocumento = NumeroDocumento;
            ServicioSegip.ServiceReference1.BuscarPersonaCIResponse retVal = ((ServicioSegip.ServiceReference1.WebService1Soap)(this)).BuscarPersonaCI(inValue);
            return retVal.Body.BuscarPersonaCIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioSegip.ServiceReference1.BuscarPersonaCIResponse> ServicioSegip.ServiceReference1.WebService1Soap.BuscarPersonaCIAsync(ServicioSegip.ServiceReference1.BuscarPersonaCIRequest request) {
            return base.Channel.BuscarPersonaCIAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioSegip.ServiceReference1.BuscarPersonaCIResponse> BuscarPersonaCIAsync(string NumeroDocumento) {
            ServicioSegip.ServiceReference1.BuscarPersonaCIRequest inValue = new ServicioSegip.ServiceReference1.BuscarPersonaCIRequest();
            inValue.Body = new ServicioSegip.ServiceReference1.BuscarPersonaCIRequestBody();
            inValue.Body.NumeroDocumento = NumeroDocumento;
            return ((ServicioSegip.ServiceReference1.WebService1Soap)(this)).BuscarPersonaCIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicioSegip.ServiceReference1.BuscarPersonasResponse ServicioSegip.ServiceReference1.WebService1Soap.BuscarPersonas(ServicioSegip.ServiceReference1.BuscarPersonasRequest request) {
            return base.Channel.BuscarPersonas(request);
        }
        
        public ServicioSegip.ServiceReference1.Persona[] BuscarPersonas(string PrimerApellido, string SegundoApellido, string Nombres) {
            ServicioSegip.ServiceReference1.BuscarPersonasRequest inValue = new ServicioSegip.ServiceReference1.BuscarPersonasRequest();
            inValue.Body = new ServicioSegip.ServiceReference1.BuscarPersonasRequestBody();
            inValue.Body.PrimerApellido = PrimerApellido;
            inValue.Body.SegundoApellido = SegundoApellido;
            inValue.Body.Nombres = Nombres;
            ServicioSegip.ServiceReference1.BuscarPersonasResponse retVal = ((ServicioSegip.ServiceReference1.WebService1Soap)(this)).BuscarPersonas(inValue);
            return retVal.Body.BuscarPersonasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServicioSegip.ServiceReference1.BuscarPersonasResponse> ServicioSegip.ServiceReference1.WebService1Soap.BuscarPersonasAsync(ServicioSegip.ServiceReference1.BuscarPersonasRequest request) {
            return base.Channel.BuscarPersonasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServicioSegip.ServiceReference1.BuscarPersonasResponse> BuscarPersonasAsync(string PrimerApellido, string SegundoApellido, string Nombres) {
            ServicioSegip.ServiceReference1.BuscarPersonasRequest inValue = new ServicioSegip.ServiceReference1.BuscarPersonasRequest();
            inValue.Body = new ServicioSegip.ServiceReference1.BuscarPersonasRequestBody();
            inValue.Body.PrimerApellido = PrimerApellido;
            inValue.Body.SegundoApellido = SegundoApellido;
            inValue.Body.Nombres = Nombres;
            return ((ServicioSegip.ServiceReference1.WebService1Soap)(this)).BuscarPersonasAsync(inValue);
        }
    }
}
