//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteEscritorio.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estudiante", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Estudiante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarreraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SemestreField;
        
        private double PromedioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TutorAsignadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoTutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoTutorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CI {
            get {
                return this.CIField;
            }
            set {
                if ((object.ReferenceEquals(this.CIField, value) != true)) {
                    this.CIField = value;
                    this.RaisePropertyChanged("CI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Carrera {
            get {
                return this.CarreraField;
            }
            set {
                if ((object.ReferenceEquals(this.CarreraField, value) != true)) {
                    this.CarreraField = value;
                    this.RaisePropertyChanged("Carrera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Semestre {
            get {
                return this.SemestreField;
            }
            set {
                if ((object.ReferenceEquals(this.SemestreField, value) != true)) {
                    this.SemestreField = value;
                    this.RaisePropertyChanged("Semestre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double Promedio {
            get {
                return this.PromedioField;
            }
            set {
                if ((this.PromedioField.Equals(value) != true)) {
                    this.PromedioField = value;
                    this.RaisePropertyChanged("Promedio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TutorAsignado {
            get {
                return this.TutorAsignadoField;
            }
            set {
                if ((object.ReferenceEquals(this.TutorAsignadoField, value) != true)) {
                    this.TutorAsignadoField = value;
                    this.RaisePropertyChanged("TutorAsignado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CorreoTutor {
            get {
                return this.CorreoTutorField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoTutorField, value) != true)) {
                    this.CorreoTutorField = value;
                    this.RaisePropertyChanged("CorreoTutor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string TelefonoTutor {
            get {
                return this.TelefonoTutorField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoTutorField, value) != true)) {
                    this.TelefonoTutorField = value;
                    this.RaisePropertyChanged("TelefonoTutor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CI del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatosAcademicos", ReplyAction="*")]
        ClienteEscritorio.ServiceReference1.ObtenerDatosAcademicosResponse ObtenerDatosAcademicos(ClienteEscritorio.ServiceReference1.ObtenerDatosAcademicosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatosAcademicos", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteEscritorio.ServiceReference1.ObtenerDatosAcademicosResponse> ObtenerDatosAcademicosAsync(ClienteEscritorio.ServiceReference1.ObtenerDatosAcademicosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CI del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatosTutor", ReplyAction="*")]
        ClienteEscritorio.ServiceReference1.ObtenerDatosTutorResponse ObtenerDatosTutor(ClienteEscritorio.ServiceReference1.ObtenerDatosTutorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatosTutor", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteEscritorio.ServiceReference1.ObtenerDatosTutorResponse> ObtenerDatosTutorAsync(ClienteEscritorio.ServiceReference1.ObtenerDatosTutorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosAcademicosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatosAcademicos", Namespace="http://tempuri.org/", Order=0)]
        public ClienteEscritorio.ServiceReference1.ObtenerDatosAcademicosRequestBody Body;
        
        public ObtenerDatosAcademicosRequest() {
        }
        
        public ObtenerDatosAcademicosRequest(ClienteEscritorio.ServiceReference1.ObtenerDatosAcademicosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosAcademicosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CI;
        
        public ObtenerDatosAcademicosRequestBody() {
        }
        
        public ObtenerDatosAcademicosRequestBody(string CI) {
            this.CI = CI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosAcademicosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatosAcademicosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteEscritorio.ServiceReference1.ObtenerDatosAcademicosResponseBody Body;
        
        public ObtenerDatosAcademicosResponse() {
        }
        
        public ObtenerDatosAcademicosResponse(ClienteEscritorio.ServiceReference1.ObtenerDatosAcademicosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosAcademicosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClienteEscritorio.ServiceReference1.Estudiante ObtenerDatosAcademicosResult;
        
        public ObtenerDatosAcademicosResponseBody() {
        }
        
        public ObtenerDatosAcademicosResponseBody(ClienteEscritorio.ServiceReference1.Estudiante ObtenerDatosAcademicosResult) {
            this.ObtenerDatosAcademicosResult = ObtenerDatosAcademicosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosTutorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatosTutor", Namespace="http://tempuri.org/", Order=0)]
        public ClienteEscritorio.ServiceReference1.ObtenerDatosTutorRequestBody Body;
        
        public ObtenerDatosTutorRequest() {
        }
        
        public ObtenerDatosTutorRequest(ClienteEscritorio.ServiceReference1.ObtenerDatosTutorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosTutorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CI;
        
        public ObtenerDatosTutorRequestBody() {
        }
        
        public ObtenerDatosTutorRequestBody(string CI) {
            this.CI = CI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosTutorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatosTutorResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteEscritorio.ServiceReference1.ObtenerDatosTutorResponseBody Body;
        
        public ObtenerDatosTutorResponse() {
        }
        
        public ObtenerDatosTutorResponse(ClienteEscritorio.ServiceReference1.ObtenerDatosTutorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosTutorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClienteEscritorio.ServiceReference1.Estudiante ObtenerDatosTutorResult;
        
        public ObtenerDatosTutorResponseBody() {
        }
        
        public ObtenerDatosTutorResponseBody(ClienteEscritorio.ServiceReference1.Estudiante ObtenerDatosTutorResult) {
            this.ObtenerDatosTutorResult = ObtenerDatosTutorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ClienteEscritorio.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ClienteEscritorio.ServiceReference1.WebService1Soap>, ClienteEscritorio.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteEscritorio.ServiceReference1.ObtenerDatosAcademicosResponse ClienteEscritorio.ServiceReference1.WebService1Soap.ObtenerDatosAcademicos(ClienteEscritorio.ServiceReference1.ObtenerDatosAcademicosRequest request) {
            return base.Channel.ObtenerDatosAcademicos(request);
        }
        
        public ClienteEscritorio.ServiceReference1.Estudiante ObtenerDatosAcademicos(string CI) {
            ClienteEscritorio.ServiceReference1.ObtenerDatosAcademicosRequest inValue = new ClienteEscritorio.ServiceReference1.ObtenerDatosAcademicosRequest();
            inValue.Body = new ClienteEscritorio.ServiceReference1.ObtenerDatosAcademicosRequestBody();
            inValue.Body.CI = CI;
            ClienteEscritorio.ServiceReference1.ObtenerDatosAcademicosResponse retVal = ((ClienteEscritorio.ServiceReference1.WebService1Soap)(this)).ObtenerDatosAcademicos(inValue);
            return retVal.Body.ObtenerDatosAcademicosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteEscritorio.ServiceReference1.ObtenerDatosAcademicosResponse> ClienteEscritorio.ServiceReference1.WebService1Soap.ObtenerDatosAcademicosAsync(ClienteEscritorio.ServiceReference1.ObtenerDatosAcademicosRequest request) {
            return base.Channel.ObtenerDatosAcademicosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteEscritorio.ServiceReference1.ObtenerDatosAcademicosResponse> ObtenerDatosAcademicosAsync(string CI) {
            ClienteEscritorio.ServiceReference1.ObtenerDatosAcademicosRequest inValue = new ClienteEscritorio.ServiceReference1.ObtenerDatosAcademicosRequest();
            inValue.Body = new ClienteEscritorio.ServiceReference1.ObtenerDatosAcademicosRequestBody();
            inValue.Body.CI = CI;
            return ((ClienteEscritorio.ServiceReference1.WebService1Soap)(this)).ObtenerDatosAcademicosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteEscritorio.ServiceReference1.ObtenerDatosTutorResponse ClienteEscritorio.ServiceReference1.WebService1Soap.ObtenerDatosTutor(ClienteEscritorio.ServiceReference1.ObtenerDatosTutorRequest request) {
            return base.Channel.ObtenerDatosTutor(request);
        }
        
        public ClienteEscritorio.ServiceReference1.Estudiante ObtenerDatosTutor(string CI) {
            ClienteEscritorio.ServiceReference1.ObtenerDatosTutorRequest inValue = new ClienteEscritorio.ServiceReference1.ObtenerDatosTutorRequest();
            inValue.Body = new ClienteEscritorio.ServiceReference1.ObtenerDatosTutorRequestBody();
            inValue.Body.CI = CI;
            ClienteEscritorio.ServiceReference1.ObtenerDatosTutorResponse retVal = ((ClienteEscritorio.ServiceReference1.WebService1Soap)(this)).ObtenerDatosTutor(inValue);
            return retVal.Body.ObtenerDatosTutorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteEscritorio.ServiceReference1.ObtenerDatosTutorResponse> ClienteEscritorio.ServiceReference1.WebService1Soap.ObtenerDatosTutorAsync(ClienteEscritorio.ServiceReference1.ObtenerDatosTutorRequest request) {
            return base.Channel.ObtenerDatosTutorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteEscritorio.ServiceReference1.ObtenerDatosTutorResponse> ObtenerDatosTutorAsync(string CI) {
            ClienteEscritorio.ServiceReference1.ObtenerDatosTutorRequest inValue = new ClienteEscritorio.ServiceReference1.ObtenerDatosTutorRequest();
            inValue.Body = new ClienteEscritorio.ServiceReference1.ObtenerDatosTutorRequestBody();
            inValue.Body.CI = CI;
            return ((ClienteEscritorio.ServiceReference1.WebService1Soap)(this)).ObtenerDatosTutorAsync(inValue);
        }
    }
}
