//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientePagos.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Deuda", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Deuda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpresaField;
        
        private decimal MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaField, value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CI del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerDeudas", ReplyAction="*")]
        ClientePagos.ServiceReference1.VerDeudasResponse VerDeudas(ClientePagos.ServiceReference1.VerDeudasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerDeudas", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientePagos.ServiceReference1.VerDeudasResponse> VerDeudasAsync(ClientePagos.ServiceReference1.VerDeudasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento empresa del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PagarDeuda", ReplyAction="*")]
        ClientePagos.ServiceReference1.PagarDeudaResponse PagarDeuda(ClientePagos.ServiceReference1.PagarDeudaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PagarDeuda", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientePagos.ServiceReference1.PagarDeudaResponse> PagarDeudaAsync(ClientePagos.ServiceReference1.PagarDeudaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerDeudasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerDeudas", Namespace="http://tempuri.org/", Order=0)]
        public ClientePagos.ServiceReference1.VerDeudasRequestBody Body;
        
        public VerDeudasRequest() {
        }
        
        public VerDeudasRequest(ClientePagos.ServiceReference1.VerDeudasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerDeudasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CI;
        
        public VerDeudasRequestBody() {
        }
        
        public VerDeudasRequestBody(string CI) {
            this.CI = CI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerDeudasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerDeudasResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientePagos.ServiceReference1.VerDeudasResponseBody Body;
        
        public VerDeudasResponse() {
        }
        
        public VerDeudasResponse(ClientePagos.ServiceReference1.VerDeudasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerDeudasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientePagos.ServiceReference1.Deuda[] VerDeudasResult;
        
        public VerDeudasResponseBody() {
        }
        
        public VerDeudasResponseBody(ClientePagos.ServiceReference1.Deuda[] VerDeudasResult) {
            this.VerDeudasResult = VerDeudasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagarDeudaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PagarDeuda", Namespace="http://tempuri.org/", Order=0)]
        public ClientePagos.ServiceReference1.PagarDeudaRequestBody Body;
        
        public PagarDeudaRequest() {
        }
        
        public PagarDeudaRequest(ClientePagos.ServiceReference1.PagarDeudaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PagarDeudaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idFactura;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string empresa;
        
        public PagarDeudaRequestBody() {
        }
        
        public PagarDeudaRequestBody(int idFactura, string empresa) {
            this.idFactura = idFactura;
            this.empresa = empresa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagarDeudaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PagarDeudaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientePagos.ServiceReference1.PagarDeudaResponseBody Body;
        
        public PagarDeudaResponse() {
        }
        
        public PagarDeudaResponse(ClientePagos.ServiceReference1.PagarDeudaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PagarDeudaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PagarDeudaResult;
        
        public PagarDeudaResponseBody() {
        }
        
        public PagarDeudaResponseBody(string PagarDeudaResult) {
            this.PagarDeudaResult = PagarDeudaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ClientePagos.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ClientePagos.ServiceReference1.WebService1Soap>, ClientePagos.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientePagos.ServiceReference1.VerDeudasResponse ClientePagos.ServiceReference1.WebService1Soap.VerDeudas(ClientePagos.ServiceReference1.VerDeudasRequest request) {
            return base.Channel.VerDeudas(request);
        }
        
        public ClientePagos.ServiceReference1.Deuda[] VerDeudas(string CI) {
            ClientePagos.ServiceReference1.VerDeudasRequest inValue = new ClientePagos.ServiceReference1.VerDeudasRequest();
            inValue.Body = new ClientePagos.ServiceReference1.VerDeudasRequestBody();
            inValue.Body.CI = CI;
            ClientePagos.ServiceReference1.VerDeudasResponse retVal = ((ClientePagos.ServiceReference1.WebService1Soap)(this)).VerDeudas(inValue);
            return retVal.Body.VerDeudasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientePagos.ServiceReference1.VerDeudasResponse> ClientePagos.ServiceReference1.WebService1Soap.VerDeudasAsync(ClientePagos.ServiceReference1.VerDeudasRequest request) {
            return base.Channel.VerDeudasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientePagos.ServiceReference1.VerDeudasResponse> VerDeudasAsync(string CI) {
            ClientePagos.ServiceReference1.VerDeudasRequest inValue = new ClientePagos.ServiceReference1.VerDeudasRequest();
            inValue.Body = new ClientePagos.ServiceReference1.VerDeudasRequestBody();
            inValue.Body.CI = CI;
            return ((ClientePagos.ServiceReference1.WebService1Soap)(this)).VerDeudasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientePagos.ServiceReference1.PagarDeudaResponse ClientePagos.ServiceReference1.WebService1Soap.PagarDeuda(ClientePagos.ServiceReference1.PagarDeudaRequest request) {
            return base.Channel.PagarDeuda(request);
        }
        
        public string PagarDeuda(int idFactura, string empresa) {
            ClientePagos.ServiceReference1.PagarDeudaRequest inValue = new ClientePagos.ServiceReference1.PagarDeudaRequest();
            inValue.Body = new ClientePagos.ServiceReference1.PagarDeudaRequestBody();
            inValue.Body.idFactura = idFactura;
            inValue.Body.empresa = empresa;
            ClientePagos.ServiceReference1.PagarDeudaResponse retVal = ((ClientePagos.ServiceReference1.WebService1Soap)(this)).PagarDeuda(inValue);
            return retVal.Body.PagarDeudaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientePagos.ServiceReference1.PagarDeudaResponse> ClientePagos.ServiceReference1.WebService1Soap.PagarDeudaAsync(ClientePagos.ServiceReference1.PagarDeudaRequest request) {
            return base.Channel.PagarDeudaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientePagos.ServiceReference1.PagarDeudaResponse> PagarDeudaAsync(int idFactura, string empresa) {
            ClientePagos.ServiceReference1.PagarDeudaRequest inValue = new ClientePagos.ServiceReference1.PagarDeudaRequest();
            inValue.Body = new ClientePagos.ServiceReference1.PagarDeudaRequestBody();
            inValue.Body.idFactura = idFactura;
            inValue.Body.empresa = empresa;
            return ((ClientePagos.ServiceReference1.WebService1Soap)(this)).PagarDeudaAsync(inValue);
        }
    }
}
