'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceReference1
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Persona", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Persona
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CiField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombresField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PrimerApellidoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SegundoApellidoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Id() As Integer
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property Ci() As String
            Get
                Return Me.CiField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CiField, value) <> true) Then
                    Me.CiField = value
                    Me.RaisePropertyChanged("Ci")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property Nombres() As String
            Get
                Return Me.NombresField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombresField, value) <> true) Then
                    Me.NombresField = value
                    Me.RaisePropertyChanged("Nombres")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property PrimerApellido() As String
            Get
                Return Me.PrimerApellidoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PrimerApellidoField, value) <> true) Then
                    Me.PrimerApellidoField = value
                    Me.RaisePropertyChanged("PrimerApellido")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property SegundoApellido() As String
            Get
                Return Me.SegundoApellidoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SegundoApellidoField, value) <> true) Then
                    Me.SegundoApellidoField = value
                    Me.RaisePropertyChanged("SegundoApellido")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.WebService1Soap")>  _
    Public Interface WebService1Soap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NumeroDocumento del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/BuscarPersonaCI", ReplyAction:="*")>  _
        Function BuscarPersonaCI(ByVal request As ServiceReference1.BuscarPersonaCIRequest) As ServiceReference1.BuscarPersonaCIResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/BuscarPersonaCI", ReplyAction:="*")>  _
        Function BuscarPersonaCIAsync(ByVal request As ServiceReference1.BuscarPersonaCIRequest) As System.Threading.Tasks.Task(Of ServiceReference1.BuscarPersonaCIResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento PrimerApellido del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/BuscarPersonas", ReplyAction:="*")>  _
        Function BuscarPersonas(ByVal request As ServiceReference1.BuscarPersonasRequest) As ServiceReference1.BuscarPersonasResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/BuscarPersonas", ReplyAction:="*")>  _
        Function BuscarPersonasAsync(ByVal request As ServiceReference1.BuscarPersonasRequest) As System.Threading.Tasks.Task(Of ServiceReference1.BuscarPersonasResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class BuscarPersonaCIRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="BuscarPersonaCI", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.BuscarPersonaCIRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.BuscarPersonaCIRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class BuscarPersonaCIRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public NumeroDocumento As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal NumeroDocumento As String)
            MyBase.New
            Me.NumeroDocumento = NumeroDocumento
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class BuscarPersonaCIResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="BuscarPersonaCIResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.BuscarPersonaCIResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.BuscarPersonaCIResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class BuscarPersonaCIResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public BuscarPersonaCIResult As ServiceReference1.Persona
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal BuscarPersonaCIResult As ServiceReference1.Persona)
            MyBase.New
            Me.BuscarPersonaCIResult = BuscarPersonaCIResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class BuscarPersonasRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="BuscarPersonas", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.BuscarPersonasRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.BuscarPersonasRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class BuscarPersonasRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public PrimerApellido As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public SegundoApellido As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Nombres As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PrimerApellido As String, ByVal SegundoApellido As String, ByVal Nombres As String)
            MyBase.New
            Me.PrimerApellido = PrimerApellido
            Me.SegundoApellido = SegundoApellido
            Me.Nombres = Nombres
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class BuscarPersonasResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="BuscarPersonasResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.BuscarPersonasResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.BuscarPersonasResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class BuscarPersonasResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public BuscarPersonasResult() As ServiceReference1.Persona
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal BuscarPersonasResult() As ServiceReference1.Persona)
            MyBase.New
            Me.BuscarPersonasResult = BuscarPersonasResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebService1SoapChannel
        Inherits ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebService1SoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.WebService1Soap)
        Implements ServiceReference1.WebService1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_WebService1Soap_BuscarPersonaCI(ByVal request As ServiceReference1.BuscarPersonaCIRequest) As ServiceReference1.BuscarPersonaCIResponse Implements ServiceReference1.WebService1Soap.BuscarPersonaCI
            Return MyBase.Channel.BuscarPersonaCI(request)
        End Function
        
        Public Function BuscarPersonaCI(ByVal NumeroDocumento As String) As ServiceReference1.Persona
            Dim inValue As ServiceReference1.BuscarPersonaCIRequest = New ServiceReference1.BuscarPersonaCIRequest()
            inValue.Body = New ServiceReference1.BuscarPersonaCIRequestBody()
            inValue.Body.NumeroDocumento = NumeroDocumento
            Dim retVal As ServiceReference1.BuscarPersonaCIResponse = CType(Me,ServiceReference1.WebService1Soap).BuscarPersonaCI(inValue)
            Return retVal.Body.BuscarPersonaCIResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_WebService1Soap_BuscarPersonaCIAsync(ByVal request As ServiceReference1.BuscarPersonaCIRequest) As System.Threading.Tasks.Task(Of ServiceReference1.BuscarPersonaCIResponse) Implements ServiceReference1.WebService1Soap.BuscarPersonaCIAsync
            Return MyBase.Channel.BuscarPersonaCIAsync(request)
        End Function
        
        Public Function BuscarPersonaCIAsync(ByVal NumeroDocumento As String) As System.Threading.Tasks.Task(Of ServiceReference1.BuscarPersonaCIResponse)
            Dim inValue As ServiceReference1.BuscarPersonaCIRequest = New ServiceReference1.BuscarPersonaCIRequest()
            inValue.Body = New ServiceReference1.BuscarPersonaCIRequestBody()
            inValue.Body.NumeroDocumento = NumeroDocumento
            Return CType(Me,ServiceReference1.WebService1Soap).BuscarPersonaCIAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_WebService1Soap_BuscarPersonas(ByVal request As ServiceReference1.BuscarPersonasRequest) As ServiceReference1.BuscarPersonasResponse Implements ServiceReference1.WebService1Soap.BuscarPersonas
            Return MyBase.Channel.BuscarPersonas(request)
        End Function
        
        Public Function BuscarPersonas(ByVal PrimerApellido As String, ByVal SegundoApellido As String, ByVal Nombres As String) As ServiceReference1.Persona()
            Dim inValue As ServiceReference1.BuscarPersonasRequest = New ServiceReference1.BuscarPersonasRequest()
            inValue.Body = New ServiceReference1.BuscarPersonasRequestBody()
            inValue.Body.PrimerApellido = PrimerApellido
            inValue.Body.SegundoApellido = SegundoApellido
            inValue.Body.Nombres = Nombres
            Dim retVal As ServiceReference1.BuscarPersonasResponse = CType(Me,ServiceReference1.WebService1Soap).BuscarPersonas(inValue)
            Return retVal.Body.BuscarPersonasResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_WebService1Soap_BuscarPersonasAsync(ByVal request As ServiceReference1.BuscarPersonasRequest) As System.Threading.Tasks.Task(Of ServiceReference1.BuscarPersonasResponse) Implements ServiceReference1.WebService1Soap.BuscarPersonasAsync
            Return MyBase.Channel.BuscarPersonasAsync(request)
        End Function
        
        Public Function BuscarPersonasAsync(ByVal PrimerApellido As String, ByVal SegundoApellido As String, ByVal Nombres As String) As System.Threading.Tasks.Task(Of ServiceReference1.BuscarPersonasResponse)
            Dim inValue As ServiceReference1.BuscarPersonasRequest = New ServiceReference1.BuscarPersonasRequest()
            inValue.Body = New ServiceReference1.BuscarPersonasRequestBody()
            inValue.Body.PrimerApellido = PrimerApellido
            inValue.Body.SegundoApellido = SegundoApellido
            inValue.Body.Nombres = Nombres
            Return CType(Me,ServiceReference1.WebService1Soap).BuscarPersonasAsync(inValue)
        End Function
    End Class
End Namespace
